;;; window-jump-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from window-jump.el

(autoload 'window-jump-left "window-jump" "\
Move to the window to the left of the current window." t)
(autoload 'window-jump-right "window-jump" "\
Move to the window to the right of the current window." t)
(autoload 'window-jump-down "window-jump" "\
Move to the window below the current window." t)
(autoload 'window-jump-up "window-jump" "\
Move to the window above the current window." t)
(register-definition-prefixes "window-jump" '("-wj-inf" "window-jump" "wj-"))

;;; End of scraped data

(provide 'window-jump-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; window-jump-autoloads.el ends here
